Aws configuration
Sam-Shulman/t-stop-reviews pull request #8
Opened 2023-05-05 14:49 UTC by juliaconnor2000

configured files to accept files through aws and show image files in form page, created migration for image url column for newStationForm
https://www.loom.com/share/29cd23a868b74e099bafc1adda5f5088

2023-05-05 17:20 UTC, nwalberts requested changes

2023-05-05 17:20 UTC, nwalberts commented on client/src/components/newStationForm.js
> +        imgUrl: acceptedImage[0]
indent lines 66 and 67 ig im not mistaken

2023-05-05 17:20 UTC, nwalberts commented on client/src/components/newStationForm.js
> +        ])
we wont to avoid setting lis into state. You can instead focus on just storing the accepted image path and size in state

2023-05-05 17:20 UTC, nwalberts commented on client/src/components/newStationForm.js
> +                />
fix indentation, and make sure input is indented in below the label

2023-05-05 17:20 UTC, nwalberts commented on server/src/routes/api/v1/stationRouter.js
> +        console.log(req.file.location)
remove console.log

2023-05-05 18:59 UTC, rlahey commented on client/src/components/newStationForm.js
> +        ])
Do you want us to use <p> tags instead or do we not want any tags there?

2023-05-08 20:37 UTC, cooperdutfield approved these changes
good

2023-05-08 20:55 UTC, dovakeen118 reviewed
small change to the validations, nice work!

2023-05-08 20:55 UTC, dovakeen118 commented on server/src/models/Station.js
> +                imgUrl: { type: ["string", "object"] }
will only be a string in our database - we want to avoid saving objects in postgres databases

2023-05-08 21:04 UTC, merged